### ISSUE TITLE
Allow NULL for LastLoggedOnUser

### ISSUE THREAD

**Issue by mt7479** [AndersRodland/ConfigMgrClientHealth#14]
I was playing around with the webservice yesterday but hit some 500 errors with a couple of clients while others seemed to work fine. Took me far to long to figure out that the machines in case where virtual machines that never have seen a console login hence LastLoggedOnUser was NULL.

Only after figuring out how to enable logging I got presented the following traceback:

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'LastLoggedOnUser', table 'ClientHealth.dbo.Clients'; column does not allow nulls. UPDATE fails.
```

https://github.com/AndersRodland/ConfigMgrClientHealth/blob/6586b41f96b9c4b9d51e312f9c6472978e4a1e3d/CreateDatabase.sql#L87

Not sure whats the rationale behind not allowing NULL for LastLoggendOnUser.

Anyway thanks for your script, it's lifesaver!

**Comment by AndersRodland** [comment]
Thank you for reporting this, it makes perfect sense to allow null. It will be implemented in the next version

**Comment by AndersRodland** [comment]
Implemented in development version now. It will be included in the next version.
