### ISSUE TITLE
Character esc for <ClientInstallProperty> /skipprereq

### ISSUE THREAD

**Issue by garetjax67** [AndersRodland/ConfigMgrClientHealth#50]
in the config file if you leverage the the /skipprereq with multiple pre-reqs using the semicolon separator:
<ClientInstallProperty>/skipprereq:dotnetfx40_client_x86_x64.exe;silverlight.exe</ClientInstallProperty>
The script generates a error about "silverlight.exe" unknown cmdlet, without digging through the script I suspected it was due to the semicolon not being escaped.  So by adding the 'tick' escape character to the property:
<ClientInstallProperty>/skipprereq:dotnetfx40_client_x86_x64.exe`;silverlight.exe</ClientInstallProperty>

The script proceeds with the installation of the CCM client.  

This fix could be handled in documentation, but might be nice to handle internally to allow the switch to leverage the ";"

**Comment by AndersRodland** [comment]
Thank you for this feedback. This is now fixed in my internal development code, and fix is included in version 0.8.3 when it's released.
