### ISSUE TITLE
[ConfigMgrClientHealth v2] Missing method for adding devices

### ISSUE THREAD

**Issue by Xento** [AndersRodland/ConfigMgrClientHealth#56]
I wanted to implement your script but I noticed that you only implement a PUT function to update existing records.
I think the POST method for adding new devices is missing in the new version.
I even looked into the code of the webservice ;-)

**Comment by AndersRodland** [comment]
Thank you for this. I'm fixing this asap and new build will be out in a few
minutes. I just need to test it. first

**Comment by AndersRodland** [comment]
This is fixed in 2.0.1. Thank you very much
