### ISSUE TITLE
Is the source code for the web service available?

### ISSUE THREAD

**Issue by shawnzzzy** [AndersRodland/ConfigMgrClientHealth#63]
Is the source code for the web service available?
Not for any reason in particular other than programming learning opportunities and additional contributor assistance.

**Comment by AndersRodland** [comment]
hi the source code for the webservice is available here: https://github.com/AndersRodland/ConfigMgrClientHealthWebservice

**Comment by shawnzzzy** [comment]
Thanks! 👍
