### ISSUE TITLE
Error in parenthesis in line 3120

### ISSUE THREAD

**Issue by regispicanco** [AndersRodland/ConfigMgrClientHealth#7]
Hi, I think there is an error with parenthesis in line 3120.

If I set SQL Enable="FALSE" in config.xml, the comando Update-SQL is executed.

I think the correct condition of the IF is:

    if (($SQLLogging -like 'true') -and (($Webservice -eq $null) -or ($Webservice -eq ""))) {

And Thanks for this script!

**Comment by AndersRodland** [comment]
Thank you for this feedback. I will do proper testing and make sure this works correctly

**Comment by rmoreas** [comment]
Seems to be fixed in commit da09e400d36099b92791b2c1b1929697303e79a5. When will this 0.8.2 version be released on https://gallery.technet.microsoft.com/ConfigMgr-Client-Health-ccd00bd7 ?

**Comment by AndersRodland** [comment]
Hi I will release 0.8.2 in September 2019, it really should have been
released a long time ago. The focus on moving config.xml into sql/console
extension is the main reason for the delay, but I will move it out of the
next release so I can get it out quicker.
