### ISSUE TITLE
Updating DB using Webservice

### ISSUE THREAD

**Issue by WittyDingo** [AndersRodland/ConfigMgrClientHealth#75]
I have a need to collect and store in db some extra information.
I created new column in db and customized ConfigMgrClientHealth script accordingly. 
After running script new/custom $Log parameter is collected.
Than I`m calling Update-Webservice function with proper switches -Uri and -Log, all of the parameters are updated in db besides my custom one. 
Does webservice have got some limitations updating clienthealth db?? $Log parameters are hardcoded into webapp??
What am I missing??

Any help is appreciated.

**Comment by craig-jarvis** [comment]
It has to do with the code in the webservice itself.

The webservice will be internally converting fields received to database entries. Probably via entity framework. Summary version, if the webservice isn't coded to handle your extra field, it won't get to the DB.

**Comment by WittyDingo** [comment]
Hello @C-J1 

Thank you for your response and for confirmation.
This is just like I thought.
This [video](https://youtu.be/Gfa93LE3K2A) shows how it works.

**Comment by cfreeman21** [comment]
@WittyDingo Was you able to get this working by updating the webservice if so, can you share your steps?
