### ISSUE TITLE
v0.8.0 doesn't include updated client version in SQL output

### ISSUE THREAD

**Issue by jholl016** [AndersRodland/ConfigMgrClientHealth#9]
I noticed in my SQL reports that clients were installing a client update, but the old/previous client version number was still being listed for that host.  This seems to be due to the fact that the ClientVersion property of the $log object does not get updated after the client installer is run.  I guess it's possible that this is the intended behavior, but it seemed un-intuitive to me.  To make this behave the way I wanted, I added these lines just before the log/sql output steps:
```
# Get installed version again, in case we updated it
$installedVersion = Get-ClientVersion
$log.ClientVersion = $installedVersion
```
Now the SQL Client table accurately shows the client version as it stands _after_ the health script runs, rather than what it was _before_ the script ran, which seems more intuitive to me.  Just sharing in case anyone else cares :).

**Comment by AndersRodland** [comment]
Thank you for reporting this issue. It has been resolved in the development version now and will be part of the next version.
